version: '3.8'

services:
  web-notes-php-fpm:
    container_name: web-notes-php
    build:
      context: ./php-fpm
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - MARKDOWN_DIRECTORY=${MARKDOWN_DIRECTORY}
      - GIT_NOTES_REPOSITORY=${GIT_NOTES_REPOSITORY}
    volumes:
      - ../src:/var/www

  web-notes-nginx:
    container_name: web-notes-nginx
    build:
      context: ./nginx
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - web-notes-php-fpm
    # If you want to expose port 80 to the host
    # ports:
    #   - "80:80"

networks:
  default:
    name: web
